In [1]:
import numpy as np


In [2]:
lista=[1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
np.array(lista)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr = np.array(lista)

In [5]:
type(arr)

numpy.ndarray

In [6]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr[0]

1

In [8]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
matriz[0,2]

3

In [10]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr[0:3]

array([1, 2, 3])

In [12]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [13]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
arr[::3]

array([1, 4, 7])

In [15]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [16]:
arr[-1]

9

In [17]:
arr[-3:]

array([7, 8, 9])

In [18]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [20]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

In [21]:
matriz[::-1,::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [22]:
matriz.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])