In [1]:
import numpy as np

In [19]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [7]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [10]:
matriz = np.array([[[1,2,3],[4,5,6],[4,5,6],[4,5,6],[4,5,6]],[[1,2,3],[4,5,6],[4,5,6],[4,5,6],[4,5,6]]])
print(matriz)
matriz.ndim

[[[1 2 3]
  [4 5 6]
  [4 5 6]
  [4 5 6]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]
  [4 5 6]
  [4 5 6]
  [4 5 6]]]


3

## Agregar o eliminar dimensiones

In [11]:
vector = np.array([1,2,3],ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [12]:
expand = np.expand_dims(np.array([1,2,3]),axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [14]:
print(vector,vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 10


In [17]:
expand = np.expand_dims(np.array([1,2,3]),axis=1)
print(expand)
expand.ndim

[[1]
 [2]
 [3]]


2

In [22]:
Ejercicio = np.array([[[[[12,45],[43,65]],[[12,45],[43,65]]],[[[12,45],[43,65]],[[12,45],[43,65]]]],[[[[12,45],[43,65]],[[12,45],[43,65]]],[[[12,45],[43,65]],[[12,45],[43,65]]]]])
Ejercicio

array([[[[[12, 45],
          [43, 65]],

         [[12, 45],
          [43, 65]]],


        [[[12, 45],
          [43, 65]],

         [[12, 45],
          [43, 65]]]],



       [[[[12, 45],
          [43, 65]],

         [[12, 45],
          [43, 65]]],


        [[[12, 45],
          [43, 65]],

         [[12, 45],
          [43, 65]]]]])

In [28]:
A = np.expand_dims(Ejercicio,axis=3)
A

array([[[[[[12, 45],
           [43, 65]]],


         [[[12, 45],
           [43, 65]]]],



        [[[[12, 45],
           [43, 65]]],


         [[[12, 45],
           [43, 65]]]]],




       [[[[[12, 45],
           [43, 65]]],


         [[[12, 45],
           [43, 65]]]],



        [[[[12, 45],
           [43, 65]]],


         [[[12, 45],
           [43, 65]]]]]])