In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10,[3,2])

In [3]:
arr.shape

(3, 2)

In [4]:
arr

array([[8, 9],
       [6, 9],
       [9, 2]])

In [5]:
arr.reshape(1,6)

array([[8, 9, 6, 9, 9, 2]])

In [6]:
arr.reshape(2,3)

array([[8, 9, 6],
       [9, 9, 2]])

In [7]:
np.reshape(arr,[1,6])

array([[8, 9, 6, 9, 9, 2]])

In [8]:
arr

array([[8, 9],
       [6, 9],
       [9, 2]])

In [9]:
np.reshape(arr,[2,3],'C')

array([[8, 9, 6],
       [9, 9, 2]])

In [10]:
np.reshape(arr,[2,3],'F')

array([[8, 9, 9],
       [6, 9, 2]])

In [12]:
np.reshape(arr,[2,3],'A')

array([[8, 9, 6],
       [9, 9, 2]])

In [13]:
arr.T

array([[8, 6, 9],
       [9, 9, 2]])