In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,20,10)

In [3]:
matriz = arr.reshape(2,5)
matriz

array([[11,  2, 12, 11,  5],
       [ 7, 19,  2, 16,  5]])

In [4]:
arr

array([11,  2, 12, 11,  5,  7, 19,  2, 16,  5])

In [5]:
arr.max()

19

In [6]:
matriz.max()

19

In [7]:
matriz.max(0)

array([11, 19, 12, 16,  5])

In [8]:
arr.argmax()

6

In [11]:
matriz.argmax(0)

array([0, 1, 0, 1, 0], dtype=int64)

In [13]:
arr.min()

2

In [14]:
matriz.min()

2

In [15]:
matriz.argmin()

1

In [16]:
matriz.argmin(0)

array([1, 0, 1, 0, 0], dtype=int64)

In [17]:
arr

array([11,  2, 12, 11,  5,  7, 19,  2, 16,  5])

In [18]:
matriz

array([[11,  2, 12, 11,  5],
       [ 7, 19,  2, 16,  5]])

In [12]:
arr.ptp()

17

In [20]:
matriz.ptp(0)

array([ 4, 17, 10,  5,  0])

In [24]:
arr.sort()
arr

array([ 2,  2,  5,  5,  7, 11, 11, 12, 16, 19])

In [25]:
np.percentile(arr,50)

9.0

In [26]:
np.median(arr)

9.0

In [27]:
np.average(arr)

9.0

In [28]:
np.mean(arr)

9.0

In [29]:
np.std(arr)

5.477225575051661

In [30]:
np.var(arr)

30.0

In [33]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])
b

array([5, 6])

In [36]:
a.ndim

2

In [44]:
b.ndim

1

In [43]:
b = np.expand_dims(b,axis=0)

array([[5, 6]])

In [42]:
np.concatenate([a,b],axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)